title: Christian Mauricio Huanto Quispe
description: Long Form Jekyll theme built with SASS

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Inicio
      url: /index.html
    - title: Investigaciones
      url: /about
    - title: Contact
      url: /contact

social:
    github: ChristianMHQ
    twitter: cmhuanto
    facebook: ChristianMauricioHuantoQuispe
    email: chuanto@fen.uchile.cl
    linkedin: cmhuanto
    youtube: cmhuanto
    tumblr: i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: ChristianHuanto
